packages:
  - packages/*

catalog:
  {
    "@effect/atom-react": npm:@effect/atom-react@4.0.0-beta.43,
    "@effect/vitest": npm:@effect/vitest@4.0.0-beta.43,
    "@effect/platform-node": npm:@effect/platform-node@4.0.0-beta.43,
    "@effect/opentelemetry": npm:@effect/opentelemetry@4.0.0-beta.43,
    dfx: npm:dfx@1.0.11,
    effect: npm:effect@4.0.0-beta.43,
    vite: npm:@voidzero-dev/vite-plus-core@latest,
    vitest: npm:@voidzero-dev/vite-plus-test@latest,
    vite-plus: latest,
  }

ignoredBuiltDependencies: []
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
