/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardShiftsRouteImport } from './routes/_authenticated/dashboard/shifts'
import { Route as AuthenticatedDashboardGuildsRouteRouteImport } from './routes/_authenticated/dashboard/guilds/route'
import { Route as AuthenticatedDashboardGuildsIndexRouteImport } from './routes/_authenticated/dashboard/guilds/index'
import { Route as AuthenticatedDashboardGuildsGuildIdScheduleRouteImport } from './routes/_authenticated/dashboard/guilds/$guildId.schedule'
import { Route as AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRouteImport } from './routes/_authenticated/dashboard/guilds/$guildId.schedule.$channel/index'
import { Route as AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteImport } from './routes/_authenticated/dashboard/guilds/$guildId.schedule.$channel/_channelLayout'
import { Route as AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRouteImport } from './routes/_authenticated/dashboard/guilds/$guildId.schedule.$channel/_channelLayout/daily'
import { Route as AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRouteImport } from './routes/_authenticated/dashboard/guilds/$guildId.schedule.$channel/_channelLayout/calendar'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardShiftsRoute =
  AuthenticatedDashboardShiftsRouteImport.update({
    id: '/shifts',
    path: '/shifts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGuildsRouteRoute =
  AuthenticatedDashboardGuildsRouteRouteImport.update({
    id: '/guilds',
    path: '/guilds',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGuildsIndexRoute =
  AuthenticatedDashboardGuildsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardGuildsRouteRoute,
  } as any)
const AuthenticatedDashboardGuildsGuildIdScheduleRoute =
  AuthenticatedDashboardGuildsGuildIdScheduleRouteImport.update({
    id: '/$guildId/schedule',
    path: '/$guildId/schedule',
    getParentRoute: () => AuthenticatedDashboardGuildsRouteRoute,
  } as any)
const AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRoute =
  AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRouteImport.update({
    id: '/$channel/',
    path: '/$channel/',
    getParentRoute: () => AuthenticatedDashboardGuildsGuildIdScheduleRoute,
  } as any)
const AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRoute =
  AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteImport.update(
    {
      id: '/$channel/_channelLayout',
      path: '/$channel',
      getParentRoute: () => AuthenticatedDashboardGuildsGuildIdScheduleRoute,
    } as any,
  )
const AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute =
  AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRouteImport.update(
    {
      id: '/daily',
      path: '/daily',
      getParentRoute: () =>
        AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRoute,
    } as any,
  )
const AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute =
  AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRouteImport.update(
    {
      id: '/calendar',
      path: '/calendar',
      getParentRoute: () =>
        AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/guilds': typeof AuthenticatedDashboardGuildsRouteRouteWithChildren
  '/dashboard/shifts': typeof AuthenticatedDashboardShiftsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/guilds/': typeof AuthenticatedDashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof AuthenticatedDashboardGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel/': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRoute
  '/dashboard/guilds/$guildId/schedule/$channel/calendar': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/daily': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/shifts': typeof AuthenticatedDashboardShiftsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/guilds': typeof AuthenticatedDashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof AuthenticatedDashboardGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRoute
  '/dashboard/guilds/$guildId/schedule/$channel/calendar': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/daily': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/guilds': typeof AuthenticatedDashboardGuildsRouteRouteWithChildren
  '/_authenticated/dashboard/shifts': typeof AuthenticatedDashboardShiftsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/guilds/': typeof AuthenticatedDashboardGuildsIndexRoute
  '/_authenticated/dashboard/guilds/$guildId/schedule': typeof AuthenticatedDashboardGuildsGuildIdScheduleRouteWithChildren
  '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren
  '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRoute
  '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/calendar': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute
  '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/daily': typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/shifts'
    | '/dashboard/'
    | '/dashboard/guilds/'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel'
    | '/dashboard/guilds/$guildId/schedule/$channel/'
    | '/dashboard/guilds/$guildId/schedule/$channel/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/shifts'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel'
    | '/dashboard/guilds/$guildId/schedule/$channel/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/daily'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/guilds'
    | '/_authenticated/dashboard/shifts'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/guilds/'
    | '/_authenticated/dashboard/guilds/$guildId/schedule'
    | '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout'
    | '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/'
    | '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/calendar'
    | '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/shifts': {
      id: '/_authenticated/dashboard/shifts'
      path: '/shifts'
      fullPath: '/dashboard/shifts'
      preLoaderRoute: typeof AuthenticatedDashboardShiftsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/guilds': {
      id: '/_authenticated/dashboard/guilds'
      path: '/guilds'
      fullPath: '/dashboard/guilds'
      preLoaderRoute: typeof AuthenticatedDashboardGuildsRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/guilds/': {
      id: '/_authenticated/dashboard/guilds/'
      path: '/'
      fullPath: '/dashboard/guilds/'
      preLoaderRoute: typeof AuthenticatedDashboardGuildsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildsRouteRoute
    }
    '/_authenticated/dashboard/guilds/$guildId/schedule': {
      id: '/_authenticated/dashboard/guilds/$guildId/schedule'
      path: '/$guildId/schedule'
      fullPath: '/dashboard/guilds/$guildId/schedule'
      preLoaderRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildsRouteRoute
    }
    '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/': {
      id: '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/'
      path: '/$channel'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/'
      preLoaderRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleRoute
    }
    '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout': {
      id: '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout'
      path: '/$channel'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel'
      preLoaderRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleRoute
    }
    '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/daily': {
      id: '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/daily'
      path: '/daily'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/daily'
      preLoaderRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRoute
    }
    '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/calendar': {
      id: '/_authenticated/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/calendar'
      path: '/calendar'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/calendar'
      preLoaderRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRoute
    }
  }
}

interface AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteChildren {
  AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute
  AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute
}

const AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteChildren: AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteChildren =
  {
    AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute:
      AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute,
    AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute:
      AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute,
  }

const AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren =
  AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRoute._addFileChildren(
    AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteChildren,
  )

interface AuthenticatedDashboardGuildsGuildIdScheduleRouteChildren {
  AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren
  AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRoute
}

const AuthenticatedDashboardGuildsGuildIdScheduleRouteChildren: AuthenticatedDashboardGuildsGuildIdScheduleRouteChildren =
  {
    AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRoute:
      AuthenticatedDashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren,
    AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRoute:
      AuthenticatedDashboardGuildsGuildIdScheduleChannelIndexRoute,
  }

const AuthenticatedDashboardGuildsGuildIdScheduleRouteWithChildren =
  AuthenticatedDashboardGuildsGuildIdScheduleRoute._addFileChildren(
    AuthenticatedDashboardGuildsGuildIdScheduleRouteChildren,
  )

interface AuthenticatedDashboardGuildsRouteRouteChildren {
  AuthenticatedDashboardGuildsIndexRoute: typeof AuthenticatedDashboardGuildsIndexRoute
  AuthenticatedDashboardGuildsGuildIdScheduleRoute: typeof AuthenticatedDashboardGuildsGuildIdScheduleRouteWithChildren
}

const AuthenticatedDashboardGuildsRouteRouteChildren: AuthenticatedDashboardGuildsRouteRouteChildren =
  {
    AuthenticatedDashboardGuildsIndexRoute:
      AuthenticatedDashboardGuildsIndexRoute,
    AuthenticatedDashboardGuildsGuildIdScheduleRoute:
      AuthenticatedDashboardGuildsGuildIdScheduleRouteWithChildren,
  }

const AuthenticatedDashboardGuildsRouteRouteWithChildren =
  AuthenticatedDashboardGuildsRouteRoute._addFileChildren(
    AuthenticatedDashboardGuildsRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardGuildsRouteRoute: typeof AuthenticatedDashboardGuildsRouteRouteWithChildren
  AuthenticatedDashboardShiftsRoute: typeof AuthenticatedDashboardShiftsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardGuildsRouteRoute:
      AuthenticatedDashboardGuildsRouteRouteWithChildren,
    AuthenticatedDashboardShiftsRoute: AuthenticatedDashboardShiftsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
