/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutShiftsRouteImport } from './routes/dashboard/_layout/shifts'
import { Route as DashboardLayoutGuildsRouteRouteImport } from './routes/dashboard/_layout/guilds/route'
import { Route as DashboardLayoutGuildsIndexRouteImport } from './routes/dashboard/_layout/guilds/index'
import { Route as DashboardLayoutGuildsGuildIdScheduleRouteImport } from './routes/dashboard/_layout/guilds/$guildId.schedule'
import { Route as DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteImport } from './routes/dashboard/_layout/guilds/$guildId.schedule.$channel/_layout'
import { Route as DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRouteImport } from './routes/dashboard/_layout/guilds/$guildId.schedule.$channel/_layout/daily'
import { Route as DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRouteImport } from './routes/dashboard/_layout/guilds/$guildId.schedule.$channel/_layout/calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutShiftsRoute = DashboardLayoutShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutGuildsRouteRoute =
  DashboardLayoutGuildsRouteRouteImport.update({
    id: '/guilds',
    path: '/guilds',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutGuildsIndexRoute =
  DashboardLayoutGuildsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLayoutGuildsRouteRoute,
  } as any)
const DashboardLayoutGuildsGuildIdScheduleRoute =
  DashboardLayoutGuildsGuildIdScheduleRouteImport.update({
    id: '/$guildId/schedule',
    path: '/$guildId/schedule',
    getParentRoute: () => DashboardLayoutGuildsRouteRoute,
  } as any)
const DashboardLayoutGuildsGuildIdScheduleChannelLayoutRoute =
  DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteImport.update({
    id: '/$channel/_layout',
    path: '/$channel',
    getParentRoute: () => DashboardLayoutGuildsGuildIdScheduleRoute,
  } as any)
const DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRoute =
  DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRouteImport.update({
    id: '/daily',
    path: '/daily',
    getParentRoute: () =>
      DashboardLayoutGuildsGuildIdScheduleChannelLayoutRoute,
  } as any)
const DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRoute =
  DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () =>
      DashboardLayoutGuildsGuildIdScheduleChannelLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/guilds': typeof DashboardLayoutGuildsRouteRouteWithChildren
  '/dashboard/shifts': typeof DashboardLayoutShiftsRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/guilds/': typeof DashboardLayoutGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardLayoutGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel': typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel/calendar': typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/daily': typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/shifts': typeof DashboardLayoutShiftsRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/guilds': typeof DashboardLayoutGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardLayoutGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel': typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel/calendar': typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/daily': typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/_layout/guilds': typeof DashboardLayoutGuildsRouteRouteWithChildren
  '/dashboard/_layout/shifts': typeof DashboardLayoutShiftsRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/_layout/guilds/': typeof DashboardLayoutGuildsIndexRoute
  '/dashboard/_layout/guilds/$guildId/schedule': typeof DashboardLayoutGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout': typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteWithChildren
  '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout/calendar': typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRoute
  '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout/daily': typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/shifts'
    | '/dashboard/'
    | '/dashboard/guilds/'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel'
    | '/dashboard/guilds/$guildId/schedule/$channel/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/shifts'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel'
    | '/dashboard/guilds/$guildId/schedule/$channel/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/daily'
  id:
    | '__root__'
    | '/'
    | '/dashboard/_layout'
    | '/dashboard/_layout/guilds'
    | '/dashboard/_layout/shifts'
    | '/dashboard/_layout/'
    | '/dashboard/_layout/guilds/'
    | '/dashboard/_layout/guilds/$guildId/schedule'
    | '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout'
    | '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout/calendar'
    | '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout/daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/shifts': {
      id: '/dashboard/_layout/shifts'
      path: '/shifts'
      fullPath: '/dashboard/shifts'
      preLoaderRoute: typeof DashboardLayoutShiftsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/guilds': {
      id: '/dashboard/_layout/guilds'
      path: '/guilds'
      fullPath: '/dashboard/guilds'
      preLoaderRoute: typeof DashboardLayoutGuildsRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/guilds/': {
      id: '/dashboard/_layout/guilds/'
      path: '/'
      fullPath: '/dashboard/guilds/'
      preLoaderRoute: typeof DashboardLayoutGuildsIndexRouteImport
      parentRoute: typeof DashboardLayoutGuildsRouteRoute
    }
    '/dashboard/_layout/guilds/$guildId/schedule': {
      id: '/dashboard/_layout/guilds/$guildId/schedule'
      path: '/$guildId/schedule'
      fullPath: '/dashboard/guilds/$guildId/schedule'
      preLoaderRoute: typeof DashboardLayoutGuildsGuildIdScheduleRouteImport
      parentRoute: typeof DashboardLayoutGuildsRouteRoute
    }
    '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout': {
      id: '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout'
      path: '/$channel'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel'
      preLoaderRoute: typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteImport
      parentRoute: typeof DashboardLayoutGuildsGuildIdScheduleRoute
    }
    '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout/daily': {
      id: '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout/daily'
      path: '/daily'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/daily'
      preLoaderRoute: typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRouteImport
      parentRoute: typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutRoute
    }
    '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout/calendar': {
      id: '/dashboard/_layout/guilds/$guildId/schedule/$channel/_layout/calendar'
      path: '/calendar'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/calendar'
      preLoaderRoute: typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRouteImport
      parentRoute: typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutRoute
    }
  }
}

interface DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteChildren {
  DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRoute: typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRoute
  DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRoute: typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRoute
}

const DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteChildren: DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteChildren =
  {
    DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRoute:
      DashboardLayoutGuildsGuildIdScheduleChannelLayoutCalendarRoute,
    DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRoute:
      DashboardLayoutGuildsGuildIdScheduleChannelLayoutDailyRoute,
  }

const DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteWithChildren =
  DashboardLayoutGuildsGuildIdScheduleChannelLayoutRoute._addFileChildren(
    DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteChildren,
  )

interface DashboardLayoutGuildsGuildIdScheduleRouteChildren {
  DashboardLayoutGuildsGuildIdScheduleChannelLayoutRoute: typeof DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteWithChildren
}

const DashboardLayoutGuildsGuildIdScheduleRouteChildren: DashboardLayoutGuildsGuildIdScheduleRouteChildren =
  {
    DashboardLayoutGuildsGuildIdScheduleChannelLayoutRoute:
      DashboardLayoutGuildsGuildIdScheduleChannelLayoutRouteWithChildren,
  }

const DashboardLayoutGuildsGuildIdScheduleRouteWithChildren =
  DashboardLayoutGuildsGuildIdScheduleRoute._addFileChildren(
    DashboardLayoutGuildsGuildIdScheduleRouteChildren,
  )

interface DashboardLayoutGuildsRouteRouteChildren {
  DashboardLayoutGuildsIndexRoute: typeof DashboardLayoutGuildsIndexRoute
  DashboardLayoutGuildsGuildIdScheduleRoute: typeof DashboardLayoutGuildsGuildIdScheduleRouteWithChildren
}

const DashboardLayoutGuildsRouteRouteChildren: DashboardLayoutGuildsRouteRouteChildren =
  {
    DashboardLayoutGuildsIndexRoute: DashboardLayoutGuildsIndexRoute,
    DashboardLayoutGuildsGuildIdScheduleRoute:
      DashboardLayoutGuildsGuildIdScheduleRouteWithChildren,
  }

const DashboardLayoutGuildsRouteRouteWithChildren =
  DashboardLayoutGuildsRouteRoute._addFileChildren(
    DashboardLayoutGuildsRouteRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardLayoutGuildsRouteRoute: typeof DashboardLayoutGuildsRouteRouteWithChildren
  DashboardLayoutShiftsRoute: typeof DashboardLayoutShiftsRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutGuildsRouteRoute: DashboardLayoutGuildsRouteRouteWithChildren,
  DashboardLayoutShiftsRoute: DashboardLayoutShiftsRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
