/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardShiftsRouteImport } from './routes/dashboard/shifts'
import { Route as DashboardGuildsRouteRouteImport } from './routes/dashboard/guilds/route'
import { Route as DashboardGuildsIndexRouteImport } from './routes/dashboard/guilds/index'
import { Route as DashboardGuildsGuildIdScheduleRouteImport } from './routes/dashboard/guilds/$guildId.schedule'
import { Route as DashboardGuildsGuildIdScheduleChannelIndexRouteImport } from './routes/dashboard/guilds/$guildId.schedule.$channel/index'
import { Route as DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteImport } from './routes/dashboard/guilds/$guildId.schedule.$channel/_channelLayout'
import { Route as DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRouteImport } from './routes/dashboard/guilds/$guildId.schedule.$channel/_channelLayout/daily'
import { Route as DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRouteImport } from './routes/dashboard/guilds/$guildId.schedule.$channel/_channelLayout/calendar'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShiftsRoute = DashboardShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuildsRouteRoute = DashboardGuildsRouteRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuildsIndexRoute = DashboardGuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildsRouteRoute,
} as any)
const DashboardGuildsGuildIdScheduleRoute =
  DashboardGuildsGuildIdScheduleRouteImport.update({
    id: '/$guildId/schedule',
    path: '/$guildId/schedule',
    getParentRoute: () => DashboardGuildsRouteRoute,
  } as any)
const DashboardGuildsGuildIdScheduleChannelIndexRoute =
  DashboardGuildsGuildIdScheduleChannelIndexRouteImport.update({
    id: '/$channel/',
    path: '/$channel/',
    getParentRoute: () => DashboardGuildsGuildIdScheduleRoute,
  } as any)
const DashboardGuildsGuildIdScheduleChannelChannelLayoutRoute =
  DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteImport.update({
    id: '/$channel/_channelLayout',
    path: '/$channel',
    getParentRoute: () => DashboardGuildsGuildIdScheduleRoute,
  } as any)
const DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute =
  DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRouteImport.update({
    id: '/daily',
    path: '/daily',
    getParentRoute: () =>
      DashboardGuildsGuildIdScheduleChannelChannelLayoutRoute,
  } as any)
const DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute =
  DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () =>
      DashboardGuildsGuildIdScheduleChannelChannelLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/guilds': typeof DashboardGuildsRouteRouteWithChildren
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/guilds/': typeof DashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel': typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel/': typeof DashboardGuildsGuildIdScheduleChannelIndexRoute
  '/dashboard/guilds/$guildId/schedule/$channel/calendar': typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/daily': typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/guilds': typeof DashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel': typeof DashboardGuildsGuildIdScheduleChannelIndexRoute
  '/dashboard/guilds/$guildId/schedule/$channel/calendar': typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/daily': typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/guilds': typeof DashboardGuildsRouteRouteWithChildren
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/guilds/': typeof DashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout': typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel/': typeof DashboardGuildsGuildIdScheduleChannelIndexRoute
  '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/calendar': typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/daily': typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/shifts'
    | '/dashboard/'
    | '/dashboard/guilds/'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel'
    | '/dashboard/guilds/$guildId/schedule/$channel/'
    | '/dashboard/guilds/$guildId/schedule/$channel/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/shifts'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel'
    | '/dashboard/guilds/$guildId/schedule/$channel/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/daily'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/shifts'
    | '/dashboard/'
    | '/dashboard/guilds/'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout'
    | '/dashboard/guilds/$guildId/schedule/$channel/'
    | '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shifts': {
      id: '/dashboard/shifts'
      path: '/shifts'
      fullPath: '/dashboard/shifts'
      preLoaderRoute: typeof DashboardShiftsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guilds': {
      id: '/dashboard/guilds'
      path: '/guilds'
      fullPath: '/dashboard/guilds'
      preLoaderRoute: typeof DashboardGuildsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guilds/': {
      id: '/dashboard/guilds/'
      path: '/'
      fullPath: '/dashboard/guilds/'
      preLoaderRoute: typeof DashboardGuildsIndexRouteImport
      parentRoute: typeof DashboardGuildsRouteRoute
    }
    '/dashboard/guilds/$guildId/schedule': {
      id: '/dashboard/guilds/$guildId/schedule'
      path: '/$guildId/schedule'
      fullPath: '/dashboard/guilds/$guildId/schedule'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleRouteImport
      parentRoute: typeof DashboardGuildsRouteRoute
    }
    '/dashboard/guilds/$guildId/schedule/$channel/': {
      id: '/dashboard/guilds/$guildId/schedule/$channel/'
      path: '/$channel'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleChannelIndexRouteImport
      parentRoute: typeof DashboardGuildsGuildIdScheduleRoute
    }
    '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout': {
      id: '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout'
      path: '/$channel'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteImport
      parentRoute: typeof DashboardGuildsGuildIdScheduleRoute
    }
    '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/daily': {
      id: '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/daily'
      path: '/daily'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/daily'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRouteImport
      parentRoute: typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutRoute
    }
    '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/calendar': {
      id: '/dashboard/guilds/$guildId/schedule/$channel/_channelLayout/calendar'
      path: '/calendar'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/calendar'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRouteImport
      parentRoute: typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutRoute
    }
  }
}

interface DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteChildren {
  DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute: typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute
  DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute: typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute
}

const DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteChildren: DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteChildren =
  {
    DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute:
      DashboardGuildsGuildIdScheduleChannelChannelLayoutCalendarRoute,
    DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute:
      DashboardGuildsGuildIdScheduleChannelChannelLayoutDailyRoute,
  }

const DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren =
  DashboardGuildsGuildIdScheduleChannelChannelLayoutRoute._addFileChildren(
    DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteChildren,
  )

interface DashboardGuildsGuildIdScheduleRouteChildren {
  DashboardGuildsGuildIdScheduleChannelChannelLayoutRoute: typeof DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren
  DashboardGuildsGuildIdScheduleChannelIndexRoute: typeof DashboardGuildsGuildIdScheduleChannelIndexRoute
}

const DashboardGuildsGuildIdScheduleRouteChildren: DashboardGuildsGuildIdScheduleRouteChildren =
  {
    DashboardGuildsGuildIdScheduleChannelChannelLayoutRoute:
      DashboardGuildsGuildIdScheduleChannelChannelLayoutRouteWithChildren,
    DashboardGuildsGuildIdScheduleChannelIndexRoute:
      DashboardGuildsGuildIdScheduleChannelIndexRoute,
  }

const DashboardGuildsGuildIdScheduleRouteWithChildren =
  DashboardGuildsGuildIdScheduleRoute._addFileChildren(
    DashboardGuildsGuildIdScheduleRouteChildren,
  )

interface DashboardGuildsRouteRouteChildren {
  DashboardGuildsIndexRoute: typeof DashboardGuildsIndexRoute
  DashboardGuildsGuildIdScheduleRoute: typeof DashboardGuildsGuildIdScheduleRouteWithChildren
}

const DashboardGuildsRouteRouteChildren: DashboardGuildsRouteRouteChildren = {
  DashboardGuildsIndexRoute: DashboardGuildsIndexRoute,
  DashboardGuildsGuildIdScheduleRoute:
    DashboardGuildsGuildIdScheduleRouteWithChildren,
}

const DashboardGuildsRouteRouteWithChildren =
  DashboardGuildsRouteRoute._addFileChildren(DashboardGuildsRouteRouteChildren)

interface DashboardRouteChildren {
  DashboardGuildsRouteRoute: typeof DashboardGuildsRouteRouteWithChildren
  DashboardShiftsRoute: typeof DashboardShiftsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGuildsRouteRoute: DashboardGuildsRouteRouteWithChildren,
  DashboardShiftsRoute: DashboardShiftsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
