apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: sheet-bot-secret
    envs:
      - .env.secret
  - name: sheet-bot-secret-path
    files:
      - google-service-account.json
configMapGenerator:
generatorOptions:
  disableNameSuffixHash: true
resources:
